// <auto-generated />
using System;
using KMAP_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace KMAP_API.Migrations
{
    [DbContext(typeof(KmapContext))]
    [Migration("20200522150239_InitialEntities")]
    partial class InitialEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("KMAP_API.Models.CLE", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .HasColumnType("text");

                    b.Property<Guid?>("VehiculeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Cle");
                });

            modelBuilder.Entity("KMAP_API.Models.ENTREPRISE", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Entreprise");
                });

            modelBuilder.Entity("KMAP_API.Models.PERSONNEL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mail")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("Permis")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.Property<Guid?>("RESERVATIONId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SITEId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RESERVATIONId");

                    b.HasIndex("SITEId");

                    b.ToTable("Personnel");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PERSONNEL");
                });

            modelBuilder.Entity("KMAP_API.Models.RESERVATION", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ConfirmationCle")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("HeureDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Heurefin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SiteDestination")
                        .HasColumnType("text");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehiculeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CleId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("KMAP_API.Models.ROLE", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("KMAP_API.Models.ReservationUtilisateur", b =>
                {
                    b.Property<Guid>("IdUtilisateur")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdReservation")
                        .HasColumnType("uuid");

                    b.HasKey("IdUtilisateur", "IdReservation");

                    b.HasIndex("IdReservation");

                    b.ToTable("ReservationUtilisateur");
                });

            modelBuilder.Entity("KMAP_API.Models.SITE", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ENTREPRISEId")
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ENTREPRISEId");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("KMAP_API.Models.VEHICULE", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Modele")
                        .HasColumnType("text");

                    b.Property<int>("NbPlaces")
                        .HasColumnType("integer");

                    b.Property<int>("NbPortes")
                        .HasColumnType("integer");

                    b.Property<string>("NumImmat")
                        .HasColumnType("text");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TypeCarbu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Vehicule");
                });

            modelBuilder.Entity("KMAP_API.Models.UTILISATEUR", b =>
                {
                    b.HasBaseType("KMAP_API.Models.PERSONNEL");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.HasIndex("RoleId");

                    b.HasDiscriminator().HasValue("UTILISATEUR");
                });

            modelBuilder.Entity("KMAP_API.Models.CLE", b =>
                {
                    b.HasOne("KMAP_API.Models.VEHICULE", "Vehicule")
                        .WithMany("Cles")
                        .HasForeignKey("VehiculeId");
                });

            modelBuilder.Entity("KMAP_API.Models.PERSONNEL", b =>
                {
                    b.HasOne("KMAP_API.Models.RESERVATION", null)
                        .WithMany("Personnels")
                        .HasForeignKey("RESERVATIONId");

                    b.HasOne("KMAP_API.Models.SITE", null)
                        .WithMany("Personnels")
                        .HasForeignKey("SITEId");
                });

            modelBuilder.Entity("KMAP_API.Models.RESERVATION", b =>
                {
                    b.HasOne("KMAP_API.Models.CLE", "Cle")
                        .WithMany()
                        .HasForeignKey("CleId");

                    b.HasOne("KMAP_API.Models.UTILISATEUR", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.HasOne("KMAP_API.Models.VEHICULE", "Vehicule")
                        .WithMany("Reservations")
                        .HasForeignKey("VehiculeId");
                });

            modelBuilder.Entity("KMAP_API.Models.ReservationUtilisateur", b =>
                {
                    b.HasOne("KMAP_API.Models.RESERVATION", "Reservation")
                        .WithMany("ReservationUtilisateurs")
                        .HasForeignKey("IdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KMAP_API.Models.UTILISATEUR", "Utilisateur")
                        .WithMany("ReservationUtilisateurs")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KMAP_API.Models.SITE", b =>
                {
                    b.HasOne("KMAP_API.Models.ENTREPRISE", null)
                        .WithMany("Sites")
                        .HasForeignKey("ENTREPRISEId");
                });

            modelBuilder.Entity("KMAP_API.Models.VEHICULE", b =>
                {
                    b.HasOne("KMAP_API.Models.SITE", "Site")
                        .WithMany("Vehicules")
                        .HasForeignKey("SiteId");
                });

            modelBuilder.Entity("KMAP_API.Models.UTILISATEUR", b =>
                {
                    b.HasOne("KMAP_API.Models.ROLE", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
